address/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Location URLs
    path('create-location/', views.createLocation, name='create-location'),
    path('location-list/', views.locationList, name='location-list'),
    path('edit-location/', views.editLocation, name='edit-location'),
    path('edit-location/<int:locationId>', views.editLocation, name='edit-location'),

    # Organization URLs
    path('create-organization/', views.createOrganization, name='create-organization'),
    path('organization-list/', views.organizationList, name='organization-list'),
    path('edit-organization/', views.editOrganization, name='edit-organization'),
    path('edit-organization/<int:organizationId>', views.editOrganization, name='edit-organization')
]

fhs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='landing-page'),
    path('update-notif-status/', views.updateNotifStatus, name='update-notif-status'),
    path('user-management-area/', include('account.urls')),
    path('user-management-area/', include('job.urls')),
    path('user-management-area/', include('address.urls')),
    # path('user-management-area/', include('priority_level.urls')),
    # path('user-management-area/', include('status.urls')),
    path('user-management-area/', include('quotation.urls')),
    path('front-area/', include('fault_report.urls')),
    path('front-page/', include('front_page.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

address/models.py
from django.db import models

# Create your models here.
class Location(models.Model):
    name = models.CharField(max_length=255)
    address = models.TextField(default=None, null=True)
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)


class Organization(models.Model):
    location = models.ManyToManyField(Location, related_name='location')
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

address/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Location, Organization
from django.db import transaction
# Create your views here.
def createLocation(request):
    if request.method == 'POST':
        name = request.POST.get('location-name').strip()
        if name == '' or name == None:
            messages.error(request, 'Location name is mandatory!', extra_tags='error-create-location')
            return redirect(request.META['HTTP_REFERER'])
        address = request.POST.get('address').strip()
        if address == '':
            address = None
        isActive = request.POST.get('is-active').strip()
        if isActive == '1':
            isActive = True
        elif isActive == '0':
            isActive = False
        else:
            messages.error(request, 'Invalid input!', extra_tags='error-create-location')
            return redirect(request.META['HTTP_REFERER'])
        try:
            Location.objects.create(name=name, address=address, is_active=isActive)

            messages.success(request, 'Successfully created location', extra_tags='success-create-location')
            return redirect(request.META['HTTP_REFERER'])
        except Exception as e:
            messages.success(request, 'Something went wrong!', extra_tags='error-create-location')
            return redirect(request.META['HTTP_REFERER'])
    data = {
        'page_':'Create Location',
        'sub_menu':'Address',
        'sub_menu2':'Location'
    }
    return render(request, 'front-end/location/create-location.html', data)


def locationList(request):
    locations = Location.objects.all().order_by('name')
    data = {
        'locations':locations,
        'sub_menu':'Address',
        'sub_menu2':'Location',
        'page_':'Location List'
    }
    return render(request, 'front-end/location/location-list.html', data)


def editLocation(request, locationId=0):
    if request.method == "POST":
        locationId = request.POST.get('location-id').strip()
        if locationId == '':
            messages.error(request, 'Invalid input!', extra_tags='error-create-location')
            return redirect(request.META['HTTP_REFERER']) 
        name = request.POST.get('location-name').strip()
        if name == '':
            messages.error(request, 'Location name is a mandatory field!', extra_tags='success-edit-location')
            return redirect(request.META['HTTP_REFERER'])
        address = request.POST.get('address').strip()
        if address == '':
            address = None
        isActive = request.POST.get("is-active").strip()
        if isActive == '1':
            isActive = True
        elif isActive == '0':
            isActive = False
        else:
            messages.error(request, 'Invalid input!', extra_tags='error-create-location')
            return redirect(request.META['HTTP_REFERER'])      
    location = Location.objects.get(id=locationId)
    if request.method == 'GET':
        data = {
            'location':location,
            'page_':'Edit Location',
            'sub_menu':'Address',
            'sub_menu2':'Location'
        }
        return render(request, 'front-end/location/edit-location.html', data)
    try:
        location.name = name
        location.address = address
        location.is_active = isActive

        location.save()

        messages.success(request, 'Successfully edited location.', extra_tags='success-edit-location')
        return redirect(request.META['HTTP_REFERER'])
    except Exception as e:
        messages.error(request, 'Something went wrong!', extra_tags='error-edit-location')
        return redirect(request.META['HTTP_REFERER'])
    

def createOrganization(request):
    if request.method == 'POST':
        locations = request.POST.getlist('location-id')
        if len(locations) == 0:
            messages.error(request, 'Invalid input!', extra_tags='error-create-organization')
            return redirect(request.META['HTTP_REFERER'])
        name = request.POST.get('organization-name').strip()
        if name == '':
            messages.error(request, 'Invalid input!', extra_tags='error-create-organization')
            return redirect(request.META['HTTP_REFERER'])
        isActive = request.POST.get('is-active').strip()
        if isActive == '0':
            isActive = False
        elif isActive == '1':
            isActive = True
        else:
            messages.error(request, 'Invalid input!', extra_tags='error-create-organization')
            return redirect(request.META['HTTP_REFERER'])
        try:
            with transaction.atomic():
                organization = Organization.objects.create(name=name, is_active=isActive)
                locationIds = [int(id) for id in locations]
                organization.location.set(locationIds)
                messages.success(request, 'Successfully created organization', extra_tags='success-create-organization')
                return redirect(request.META['HTTP_REFERER'])
        except Exception as e:
            messages.error(request, 'Something went wrong!', extra_tags='error-create-organization')
            return redirect(request.META['HTTP_REFERER'])
    locations = Location.objects.filter(is_active=True).order_by('name')
    data = {
        'locations':locations,
        'page_':'Create Organization',
        'sub_menu':'Address',
        'sub_menu2':'Organization'
    }
    return render(request, 'front-end/organization/create-organization.html', data)


def organizationList(request):
    organizations = Organization.objects.all().order_by('name')
    data = {
        'organizations':organizations,
        'page_':'Organization List',
        'sub_menu':'Address',
        'sub_menu2':'Organization'
    }
    return render(request, 'front-end/organization/organization-list.html', data)


def editOrganization(request, organizationId=0):
    if request.method == "POST":
        locations = request.POST.getlist('location-id')
        if len(locations) == 0:
            messages.error(request, 'Location is mandatory!', extra_tags='error-edit-organization')
            return redirect(request.META['HTTP_REFERER'])
        locationIds = [int(id) for id in locations]
        organizationId = request.POST.get('organization-id').strip()
        if organizationId == '':
            messages.error(request, 'Invalid input!', extra_tags='error-edit-organization')
            return redirect(request.META['HTTP_REFERER'])
        name = request.POST.get('organization-name').strip()
        if name == '':
            messages.error(request, 'Invalid input!', extra_tags='error-edit-organization')
            return redirect(request.META['HTTP_REFERER'])
        isActive = request.POST.get('is-active').strip()
        if isActive == '0':
            isActive = False
        elif isActive == '1':
            isActive = True
        else:
            messages.error(request, 'Invalid input!', extra_tags='error-edit-organization')
            return redirect(request.META['HTTP_REFERER'])
    organization = Organization.objects.get(id=organizationId)
    if request.method == 'GET':
        locations = Location.objects.filter(is_active=True).order_by('name')
        selectedLocations = organization.location.all()
        selectedLocationsArr = [location.id for location in selectedLocations]
        data = {
            'locations':locations,
            'selected_locations':selectedLocationsArr,
            'organization':organization,
            'page_':'Edit Organization',
            'sub_menu':'Address',
            'sub_menu2':'Organization'
        }
        return render(request, 'front-end/organization/edit-organization.html', data)
    try:
        with transaction.atomic():
            organization.location.set(locationIds)
            organization.name = name
            organization.is_active = isActive
            organization.save()
            messages.success(request, 'Successfully edited organization', extra_tags='success-edit-organization')
            return redirect(request.META['HTTP_REFERER'])
    except Exception as e:
        messages.success(request, 'Something went wrong!', extra_tags='error-edit-organization')
        return redirect(request.META['HTTP_REFERER'])

address/templates/front-end/location/create-location.html
{% extends 'base-front-end/admin/base.html' %}
{% block title %}
  <title>{{ page_ }}</title>
{% endblock %}
{% block content %}
<!--begin::App Main-->
<main class="app-main">
  <!--begin::App Content Header-->
  <div class="app-content-header">
    <!--begin::Container-->
    <div class="container-fluid">
      <!--begin::Row-->
      <div class="row">
        <div class="col-sm-6">
          <h3 class="mb-0">{{ page_ }}</h3>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-end">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ page_ }}</li>
          </ol>
        </div>
      </div>
      <!--end::Row-->
    </div>
    <!--end::Container-->
  </div>
  <!--end::App Content Header-->
  <!--begin::App Content-->
  <div class="app-content">
    <!--begin::Container-->
    <div class="container-fluid">
      <!--begin::Row-->
      <div class="row g-4">
        <!--begin::Col-->
        <div class="col-12">
          {% for message in messages %}
            {% if message.extra_tags == 'success-create-location' %}
              <div class="callout callout-success">
                {{ message }}
              </div>
            {% elif message.extra_tags == 'error-create-location' %}
              <div class="callout callout-danger">
                {{ message }}
              </div>
            {% endif %}
          {% endfor %}
        </div>
        <!--end::Col-->
        <!--begin::Col-->
        <div class="col-md-6">
          <!--begin::Quick Example-->
          <div class="card card-primary card-outline mb-4">
            <!--begin::Form-->
            <form action="{% url 'create-location' %}" method="POST">
              {% csrf_token %}
              <!--begin::Body-->
              <div class="card-body">
                <div class="mb-3">
                  <label for="" class="form-label">Location Name</label>
                  <input type="text" name="location-name" class="form-control" id="" aria-describedby="locationName" />
                </div>
                <div class="mb-3">
                  <label for="" class="form-label">Address <small>(Optional)</small></label>
                  <textarea name="address" class="form-control" id=""></textarea>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="is-active" id="active" value="1" checked/>
                  <label class="form-check-label" for="active"> Active </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="is-active" id="inactive" value="0"/>
                  <label class="form-check-label" for="inactive"> Inactive </label>
                </div>
              </div>
              <!--end::Body-->
              <!--begin::Footer-->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Create Location</button>
              </div>
              <!--end::Footer-->
            </form>
            <!--end::Form-->
          </div>
          <!--end::Quick Example-->
        </div>
        <!--end::Col-->
        <!--begin::Col-->
        <div class="col-md-6">
        </div>
        <!--end::Col-->
      </div>
      <!--end::Row-->
    </div>
    <!--end::Container-->
  </div>
  <!--end::App Content-->
</main>
{% endblock %}

address/templates/front-end/location/edit-location.html
{% extends 'base-front-end/admin/base.html' %}
{% block title %}
  <title>{{ page_ }}</title>
{% endblock %}
{% block content %}
<!--begin::App Main-->
<main class="app-main">
  <!--begin::App Content Header-->
  <div class="app-content-header">
    <!--begin::Container-->
    <div class="container-fluid">
      <!--begin::Row-->
      <div class="row">
        <div class="col-sm-6">
          <h3 class="mb-0">{{ page_ }}</h3>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-end">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ page_ }}</li>
          </ol>
        </div>
      </div>
      <!--end::Row-->
    </div>
    <!--end::Container-->
  </div>
  <!--end::App Content Header-->
  <!--begin::App Content-->
  <div class="app-content">
    <!--begin::Container-->
    <div class="container-fluid">
      <!--begin::Row-->
      <div class="row g-4">
        <!--begin::Col-->
        <div class="col-12">
          {% for message in messages %}
            {% if message.extra_tags == 'success-edit-location' %}
              <div class="callout callout-success">
                {{ message }}
              </div>
            {% elif message.extra_tags == 'error-edit-location' %}
              <div class="callout callout-danger">
                {{ message }}
              </div>
            {% endif %}
          {% endfor %}
        </div>
        <!--end::Col-->
        <!--begin::Col-->
        <div class="col-md-6">
          <!--begin::Quick Example-->
          <div class="card card-primary card-outline mb-4">
            <!--begin::Form-->
            <form action="{% url 'edit-location' %}" method="POST">
              {% csrf_token %}
              <!--begin::Body-->
              <div class="card-body">
                <input type="hidden" name="location-id" value="{{ location.id }}">
                <div class="mb-3">
                  <label for="" class="form-label">Location Name</label>
                  <input type="text" name="location-name" value="{{ location.name }}" class="form-control" id="" aria-describedby="locationName" />
                </div>
                <div class="mb-3">
                  <label for="" class="form-label">Address <small>(Optional)</small></label>
                  <textarea name="address" class="form-control" id="">{{ location.address }}</textarea>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="is-active" id="active" value="1" {% if location.is_active == True %}checked{% endif %}/>
                  <label class="form-check-label" for="active"> Active </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="is-active" id="inactive" value="0" {% if location.is_active == False %}checked{% endif %}/>
                  <label class="form-check-label" for="inactive"> Inactive </label>
                </div>
              </div>
              <!--end::Body-->
              <!--begin::Footer-->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Update</button>
              </div>
              <!--end::Footer-->
            </form>
            <!--end::Form-->
          </div>
          <!--end::Quick Example-->
        </div>
        <!--end::Col-->
        <!--begin::Col-->
        <div class="col-md-6">
        </div>
        <!--end::Col-->
      </div>
      <!--end::Row-->
    </div>
    <!--end::Container-->
  </div>
  <!--end::App Content-->
</main>
{% endblock %}

address/templates/front-end/location/location-list.html
{% extends 'base-front-end/admin/base.html' %}
{% block title %}
  <title>{{ page_ }}</title>
{% endblock %}
{% block content %}
<!--begin::App Main-->
<main class="app-main">
  <!--begin::App Content Header-->
  <div class="app-content-header">
    <!--begin::Container-->
    <div class="container-fluid">
      <!--begin::Row-->
      <div class="row">
        <div class="col-sm-6">
          <h3 class="mb-0">{{ page_ }}</h3>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-end">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ page_ }}</li>
          </ol>
        </div>
      </div>
      <!--end::Row-->
    </div>
    <!--end::Container-->
  </div>
  <!--end::App Content Header-->
  <!--begin::App Content-->
  <div class="app-content">
    <!--begin::Container-->
    <div class="container-fluid">
      <!--begin::Row-->
      <div class="row">
        <div class="col-md-6">
          <!-- /.card -->
          <div class="card mb-4">
            <!-- /.card-header -->
            <div class="card-body p-0">
              <table class="table table-sm">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Activity</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for location in locations %}
                  <tr class="align-middle">
                    <td>{{ location.name }}</td>
                    <td>
                      {% if location.address != None %}
                        {{ location.address }}
                      {% endif %}
                    </td>
                    <td>
                      {% if location.is_active == True %}
                        <div class="badge bg-success">Active</div>
                      {% else %}
                        <div class="badge bg-info">Inactive</div>
                      {% endif %}
                    </td>
                    <td>
                      {% if perms.address.change_location %}
                        <a class="btn btn-sm btn-primary" href="{% url 'edit-location' locationId=location.id %}">Edit</a>
                      {% endif %}
                      <!-- <a class="btn btn-sm btn-danger" href="">Delete</a> -->
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
        <!-- /.col -->
      </div>
      <!--end::Row-->
    </div>
    <!--end::Container-->
  </div>
  <!--end::App Content-->
</main>
<!--end::App Main-->
{% endblock %}