account/urls.py
from django.urls import path
from . import views_admin, views_technician, views_enduser
from fault_report import views as views_fault_reports

urlpatterns = [
    path('home/', views_admin.home, name='home'),
    # Admin URLs
    path('create-admin/', views_admin.createAdmin, name='create-admin'),
    path('create-admin-internal/<str:type>', views_admin.createAdmin, name='create-admin-internal'),
    path('edit-admin/<int:adminId>', views_admin.editAdmin, name='edit-admin'),
    path('edit-admin/', views_admin.editAdmin, name='edit-admin'),
    path('delete-admin/<int:adminId>', views_admin.deleteAdmin, name='delete-admin'),
    path('admin-list/', views_admin.adminList, name='admin-list'),
    path('login-user/', views_admin.loginUser, name='login-user'),
    path('logout-admin/', views_admin.logoutAdmin, name='logout-admin'),
    path('permissions-admin/<int:adminId>', views_admin.permissionList, name='permissions-admin'),
    path('update-permissions-admin/', views_admin.updatePermissions, name='update-permissions-admin'),

    # Technician URLs
    path('create-technician/', views_technician.createTechnician, name='create-technician'),
    path('technician-list/', views_technician.technicianList, name='technician-list'),
    path('edit-technician/<int:technicianId>', views_technician.editTechnician, name='edit-technician'),
    path('edit-technician/', views_technician.editTechnician, name='edit-technician'),

    # End-user URLs
    path('create-enduser/', views_enduser.createEndUser, name='create-enduser'),
    path('activate-account/<str:code>', views_enduser.activateAccount, name='activate-account'),
    path('customer-list/', views_enduser.customerList, name='customer-list'),
    path('customer-history/<str:customerEmail>', views_enduser.customerHistory, name='customer-history'),
    path('send-change-password-link/', views_enduser.sendChangePasswordLink, name='send-change-password-link'),
    path('change-password/<str:code>', views_enduser.changePassword, name='change-password'),
    path('change-password/', views_enduser.changePassword, name='change-password'),
    path('get-loc-from-org/', views_enduser.getLocFromOrg, name='get-loc-from-org'),

    # Fault Reports URLs
    path('fault-reports/', views_fault_reports.faultReportList, name='fault-reports'),
    path('fault-reports-filter/<str:status>/<str:priorityLevel>/<str:filterTimeType>/<str:startDate>/<str:endDate>', views_fault_reports.faultReportsFilter, name='fault-reports-filter'),
    path('fault-reports-filter/', views_fault_reports.faultReportsFilter, name='fault-reports-filter')
]

fhs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='landing-page'),
    path('update-notif-status/', views.updateNotifStatus, name='update-notif-status'),
    path('user-management-area/', include('account.urls')),
    path('user-management-area/', include('job.urls')),
    path('user-management-area/', include('address.urls')),
    # path('user-management-area/', include('priority_level.urls')),
    # path('user-management-area/', include('status.urls')),
    path('user-management-area/', include('quotation.urls')),
    path('front-area/', include('fault_report.urls')),
    path('front-page/', include('front_page.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.conf import settings
from django.urls import reverse
from fhs.email_sender import sendEmail
from address.models import Organization, Location

# Create your models here.
class UserManager(BaseUserManager):


    def create_user(self, first_name, last_name, email, phone, password):
        user = self.model(
            first_name=first_name,
            last_name = last_name,
            email = email,
            phone = phone
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    

    def create_superuser(self, email, phone, password, is_superadmin=False, is_active=False, first_name="Admin", last_name="Member"):
        user = self.create_user(
            first_name=first_name,
            last_name = last_name,
            email = email,
            phone = phone,
            password = password
        )
        user.is_superadmin = is_superadmin
        user.is_active = is_active
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user
    

class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    account_number = models.CharField(max_length=7, default=None, null=True)
    email = models.CharField(max_length=255, unique=True)
    phone = models.CharField(max_length=20, unique=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, default=None, null=True)
    user_location = models.ManyToManyField(Location, related_name='user_location')

    account_activation_code = models.CharField(max_length=255, default=None, null=True)
    change_password_code = models.CharField(max_length=255, default=None, null=True)

    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    is_enduser = models.BooleanField(default=False)
    is_technician = models.BooleanField(default=False)

    is_available = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email
    
    # def has_perm(self, perm, object=None):
    #     return False
    
    def has_module_perms(self, app_label):
        return True
    

@receiver(post_save, sender=User)
def sendEmailToUser(sender, instance, created, **kwargs):
    if instance.is_enduser==True and instance.is_active == False and instance.account_activation_code != None:
        to = []
        to.append(instance.email)
        subject = "Account activation email from FHS"
        link = reverse('activate-account', args=[instance.account_activation_code])
        fullLink = f'{settings.BASIC_URL}{link}'
        body = 'front-end/emails/send-enduser-account-activation-link-email.html'
        context = {
            'receiver_name':f'{instance.first_name} {instance.last_name}',
            'full_link':fullLink
        }
        sendEmail.delay(subject=subject, body=body, context=context, to=to)

account/templates/front-end/admin/admin-list.html
{% extends 'base-front-end/admin/base.html' %}
{% block title %}
  <title>
    {{ page_ }}
  </title>
{% endblock %}
{% block content %}
<!--begin::App Main-->
<main class="app-main">
  <!--begin::App Content Header-->
  <div class="app-content-header">
    <!--begin::Container-->
    <div class="container-fluid">
      <!--begin::Row-->
      <div class="row">
        <div class="col-sm-6">
          <h3 class="mb-0">{{ page_ }}</h3>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-end">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ page_ }}</li>
          </ol>
        </div>
        <div class="col-12">
          {% for message in messages %}
            {% if message.extra_tags == 'success-admin-list' %}
              <div class="alert text-white bg-success">
                {{ message }}
              </div>
            {% elif message.extra_tags == 'error-admin-list' %}
              <div class="alert text-white bg-danger">
                {{ message }}
              </div>
            {% endif %}
          {% endfor %}
        </div>
      </div>
      <!--end::Row-->
    </div>
    <!--end::Container-->
  </div>
  <!--end::App Content Header-->
  <!--begin::App Content-->
  <div class="app-content">
    <!--begin::Container-->
    <div class="container-fluid">
      <!--begin::Row-->
      <div class="row">
        <div class="col-md-12">
          <!-- /.card -->
          <div class="card mb-4">
            <!-- /.card-header -->
            <div class="card-body p-0">
              <table class="table table-sm">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Role</th>
                    <th>Permissions</th>
                    <th>Activity</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for admin in admins %}
                  <tr class="align-middle">
                    <td>{{ admin.first_name }} {{ admin.last_name }}</td>
                    <td>
                        {% if admin.is_superadmin == True %}
                            Super Admin
                        {% else %}
                            Admin
                        {% endif %}
                    </td>
                    <td>
                      {% if perms.auth.view_permission %}
                        <a class="text-muted" href="{% url 'permissions-admin' adminId=admin.id %}">
                          {% if admin.user_permissions.count == total_permissions %}
                            All
                          {% else %}
                            {{ admin.user_permissions.count }}
                          {% endif %}
                        </a>
                      {% else %}
                        {% if admin.user_permissions.count == total_permissions %}
                          All
                        {% else %}
                          {{ admin.user_permissions.count }}
                        {% endif %}
                      {% endif %}
                    </td>
                    <td>
                      {% if admin.is_active == True %}
                        <div class="badge bg-success">Active</div>
                      {% else %}
                        <div class="badge bg-info">Inactive</div>
                      {% endif %}
                    </td>
                    <td>
                      {% if perms.account.change_user %}
                        <a class="text-primary" href="{% url 'edit-admin' adminId=admin.id %}"><i class="bi bi-pencil"></i></a>
                      {% endif %}
                      {% if perms.account.delete_user %}
                        <a type="button" data-bs-toggle="modal" data-bs-target="#deleteModal" class="text-danger" href="javascript:void(0)" onclick="deleteRecord('delete the admin?',`{% url 'delete-admin' adminId=admin.id %}`)"><i class="bi bi-trash"></i></a>
                      {% endif %}
                        <!-- <a class="btn btn-sm btn-danger" href="">Delete</a> -->
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
        <!-- /.col -->
      </div>
      <!--end::Row-->
    </div>
    <!--end::Container-->
    {% include 'base-front-end/modals/delete-modal.html' %}  
  </div>
  <!--end::App Content-->
</main>
<!--end::App Main-->
{% endblock %}

account/templates/front-end/admin/create-admin-internal.html
{% extends 'base-front-end/admin/base.html' %}
{% block title %}
  <title>
    {{ page_ }}
  </title>
{% endblock %}
{% block content %}
<!--begin::App Main-->
<main class="app-main">
  <!--begin::App Content Header-->
  <div class="app-content-header">
    <!--begin::Container-->
    <div class="container-fluid">
      <!--begin::Row-->
      <div class="row">
        <div class="col-sm-6">
          <h3 class="mb-0">{{ page_ }}</h3>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-end">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Create Admin</li>
          </ol>
        </div>
      </div>
      <!--end::Row-->
    </div>
    <!--end::Container-->
  </div>
  <!--end::App Content Header-->
  <!--begin::App Content-->
  <div class="app-content">
    <!--begin::Container-->
    <div class="container-fluid">
      <!--begin::Row-->
      <div class="row g-4">
        <div class="col-12">
          {% for message in messages %}
            {% if message.extra_tags == 'success-create-admin' %}
              <div class="callout callout-success">
                {{ message }}
              </div>
            {% elif message.extra_tags == 'error-create-admin' %}
              <div class="callout callout-danger">
                {{ message }}
              </div>
            {% endif %}
          {% endfor %}
        </div>
        <!--begin::Col-->
        <!--end::Col-->
        <!--begin::Col-->
        <div class="col-md-6">
          <!--begin::Quick Example-->
          <div class="card card-primary card-outline mb-4">
            <!--begin::Form-->
            <form action="{% url 'create-admin' %}" method="POST">
              {% csrf_token %}
              <!--begin::Body-->
              <div class="card-body">
                <div class="mb-3">
                  <label for="" class="form-label">First Name</label>
                  <input type="text" name="first-name" class="form-control" id="" aria-describedby="firstName" />
                </div>
                <div class="mb-3">
                  <label for="" class="form-label">Last Name</label>
                  <input type="text" name="last-name" class="form-control" id="" aria-describedby="lastName" />
                </div>
                <div class="mb-3">
                  <label for="" class="form-label">Email</label>
                  <input required type="text" name="email" class="form-control" id="" aria-describedby="email" />
                </div>
                <div class="mb-3">
                  <label for="" class="form-label">Phone</label>
                  <input required type="text" name="phone" class="form-control" id="" aria-describedby="phone" />
                </div>
                <div class="mb-3">
                  <label for="" class="form-label">Password</label>
                  <input required type="password" name="password" class="form-control" id="" aria-describedby="password" />
                </div>
                <div class="mb-3">
                  <label required for="" class="form-label">Retype Password</label>
                  <input type="password" name="retype-password" class="form-control" id="" aria-describedby="retypePassword" />
                </div>
              </div>
              <!--end::Body-->
              <!--begin::Footer-->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Create Admin</button>
              </div>
              <!--end::Footer-->
            </form>
            <!--end::Form-->
          </div>
          <!--end::Quick Example-->
        </div>
        <!--end::Col-->
        <!--begin::Col-->
        <div class="col-md-6">
        </div>
        <!--end::Col-->
      </div>
      <!--end::Row-->
    </div>
    <!--end::Container-->
  </div>
  <!--end::App Content-->
</main>
{% endblock %}

account/templates/front-end/admin/create-admin2.html
<html>
    <head>
        <title>Create New Admin</title>
    </head>
    <body>
        <div>
            <form action="{% url 'create-admin' %}" method="POST">
                {% csrf_token %}
                <label for="">First name</label>
                <input type="text" name="first-name">
                <label for="">Last Name</label>
                <input type="text" name="last-name">
                <label for="">Email</label>
                <input type="text" name="email">
                <label for="">Phone</label>
                <input type="text" name="phone">
                <label for="">Password</label>
                <input type="password" name="password">
                <label for="">Retype Password</label>
                <input type="password" name="retype-password">
                <button type="submit">Create</button>
            </form>
        </div>
    </body>
</html>

account/templates/front-end/admin/create-superadmin.html
{% extends 'base-front-end/admin/login-register-base.html' %}
{% block content %}
<p class="register-box-msg">Create Superadmin</p>
<form action="{% url 'create-admin' %}" method="post">
    {% csrf_token %}
    <div class="col-12">
        {% for message in messages %}
            {% if message.extra_tags == 'success-create-admin' %}
              <div class="callout callout-success">
                {{ message }}
              </div>
            {% elif message.extra_tags == 'error-create-admin' %}
              <div class="callout callout-danger">
                {{ message }}
              </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="input-group mb-1">
        <div class="form-floating">
            <input id="registerFullName" type="text" name="first-name" class="form-control" placeholder="" />
            <label for="registerFullName">First Name</label>
        </div>
        <div class="input-group-text"><span class="bi bi-person"></span></div>
    </div>
    <div class="input-group mb-1">
        <div class="form-floating">
            <input id="registerFullName" type="text" name="last-name" class="form-control" placeholder="" />
            <label for="registerFullName">Last Name</label>
        </div>
        <div class="input-group-text"><span class="bi bi-person"></span></div>
    </div>
    <div class="input-group mb-1">
        <div class="form-floating">
            <input id="registerEmail" type="email" name="email" class="form-control" placeholder="" />
            <label for="registerEmail">Email</label>
        </div>
        <div class="input-group-text"><span class="bi bi-envelope"></span></div>
    </div>
    <div class="input-group mb-1">
        <div class="form-floating">
            <input id="registerEmail" type="text" name="phone" class="form-control" placeholder="" />
            <label for="registerEmail">Phone</label>
        </div>
        <div class="input-group-text"><span class="bi bi-phone"></span></div>
    </div>
    <div class="input-group mb-1">
        <div class="form-floating">
            <input id="registerPassword" type="password" name="password" class="form-control" placeholder="" />
            <label for="registerPassword">Password</label>
        </div>
        <div class="input-group-text"><span class="bi bi-lock-fill"></span></div>
    </div>
    <div class="input-group mb-1">
        <div class="form-floating">
            <input id="registerPassword" type="password" name="retype-password" class="form-control" placeholder="" />
            <label for="registerPassword">Retype Password</label>
        </div>
        <div class="input-group-text"><span class="bi bi-lock-fill"></span></div>
    </div>
    <!--begin::Row-->
    <div class="row">
        <!-- /.col -->
        <div class="col-4">
            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-primary">Create Superadmin</button>
            </div>
        </div>
        <!-- /.col -->
    </div>
    <!--end::Row-->
</form>
{% endblock %}

account/templates/front-end/admin/edit-admin.html
{% extends 'base-front-end/admin/base.html' %}
{% block title %}
  <title>{{ page_ }}</title>
{% endblock %}
{% block content %}
<!--begin::App Main-->
<main class="app-main">
  <!--begin::App Content Header-->
  <div class="app-content-header">
    <!--begin::Container-->
    <div class="container-fluid">
      <!--begin::Row-->
      <div class="row">
        <div class="col-sm-6">
          <h3 class="mb-0">{{ page_ }}</h3>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-end">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ page_ }}</li>
          </ol>
        </div>
      </div>
      <!--end::Row-->
    </div>
    <!--end::Container-->
  </div>
  <!--end::App Content Header-->
  <!--begin::App Content-->
  <div class="app-content">
    <!--begin::Container-->
    <div class="container-fluid">
      <!--begin::Row-->
      <div class="row g-4">
        <!--begin::Col-->
        <div class="col-12">
          {% for message in messages %}
            {% if message.extra_tags == 'success-edit-admin' %}
              <div class="callout callout-success">
                {{ message }}
              </div>
            {% elif message.extra_tags == 'error-edit-admin' %}
              <div class="callout callout-danger">
                {{ message }}
              </div>
            {% endif %}
          {% endfor %}
        </div>
        <!--end::Col-->
        <!--begin::Col-->
        <div class="col-md-6">
          <!--begin::Quick Example-->
          <div class="card card-primary card-outline mb-4">
            <!--begin::Form-->
            <form action="{% url 'edit-admin' %}" method="POST">
              {% csrf_token %}
              <!--begin::Body-->
              <div class="card-body">
                <input type="hidden" name="admin-id" value="{{ admin.id }}">
                <div class="mb-3">
                  <label for="" class="form-label">First Name</label>
                  <input type="text" name="first-name" value="{{ admin.first_name }}" class="form-control" id="" aria-describedby="adminFirstName" />
                </div>
                <div class="mb-3">
                  <label for="" class="form-label">Last Name</label>
                  <input type="text" name="last-name" value="{{ admin.last_name }}" class="form-control" id="" aria-describedby="adminLastName" />
                </div>
                <div class="mb-3">
                  <label for="" class="form-label">Email</label>
                  <input type="text" name="email" value="{{ admin.email }}" class="form-control" id="" aria-describedby="adminEmail" />
                </div>
                <div class="mb-3">
                  <label for="" class="form-label">Phone</label>
                  <input type="text" name="phone" value="{{ admin.phone }}" class="form-control" id="" aria-describedby="adminPhone" />
                </div>
                <div class="mb-3">
                  <label for="" class="form-label">Password</label>
                  <input type="password" name="password" value="" class="form-control" id="" aria-describedby="adminPhone" />
                </div>
                <div class="mb-3">
                  <label for="" class="form-label">Retype Password</label>
                  <input type="password" name="retype-password" value="" class="form-control" id="" aria-describedby="adminPhone" />
                </div>
                <div class="mb-3">
                  <input type="radio" name="is-active" {% if admin.is_active == True %}checked{% endif %} value="1">Active
                  <input type="radio" name="is-active" {% if admin.is_active == False %}checked{% endif %} value="0">Inactive
                </div>
              </div>
              <!--end::Body-->
              <!--begin::Footer-->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Update</button>
              </div>
              <!--end::Footer-->
            </form>
            <!--end::Form-->
          </div>
          <!--end::Quick Example-->
        </div>
        <!--end::Col-->
        <!--begin::Col-->
        <div class="col-md-6">
        </div>
        <!--end::Col-->
      </div>
      <!--end::Row-->
    </div>
    <!--end::Container-->
  </div>
  <!--end::App Content-->
</main>
{% endblock %}

account/templates/front-end/admin/home2-admin.html
<html>
    <head>
        <title>Admin Home</title>
    </head>
    <body>
        <div>
            <a href="{% url 'logout-admin' %}">Logout</a>
        </div>
    </body>
</html>

account/templates/front-end/admin/login-admin.html
{% extends 'base-front-end/admin/login-register-base.html' %}
{% block content %}
<p class="register-box-msg">Log In</p>
<form action="{% url 'login-user' %}" method="post" onsubmit="hideButton('id-log-in', 'id-log-in-div')">
    {% csrf_token %}
    {% for message in messages %}
        {% if message.extra_tags == 'success-login-user' %}
            <div class="callout callout-success">
                {{ message }}
            </div>
        {% elif message.extra_tags == 'error-login-user' %}
            <div class="callout callout-danger">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
    <div class="input-group mb-1">
        <div class="form-floating">
            <input required id="registerEmail" type="email" name="email" class="form-control" placeholder="" />
            <label for="registerEmail">Email</label>
        </div>
        <div class="input-group-text"><span class="bi bi-envelope"></span></div>
    </div>
    <div class="input-group mb-1">
        <div class="form-floating">
            <input required id="registerPassword" type="password" name="password" class="form-control" placeholder="" />
            <label for="registerPassword">Password</label>
        </div>
        <div class="input-group-text"><span class="bi bi-lock-fill"></span></div>
    </div>
    <!--begin::Row-->
    <div class="row">
        <!-- /.col -->
        <div class="col-4">
            <div id="id-log-in-div" class="d-grid gap-2">
                <button id="id-log-in" type="submit" class="btn btn-primary">Log In</button>
            </div>
        </div>
        <!-- /.col -->
    </div>
    <!--end::Row-->
    <!--begin::Row-->
    <div class="row">
        <!-- /.col -->
        <div class="col-12 text-center">
            <div id="id-log-in-div" class="d-grid gap-2">
                <a class="text-muted" href="{% url 'send-change-password-link' %}">Forgot password?</a>
            </div>
        </div>
        <div class="col-12 text-center mt-2">
            Not registered? <a class="text-muted" href="{% url 'create-enduser' %}">Sign up</a>
        </div>
        <div class="col-12 text-center mt-2">
            OR
        </div>
        <div class="col-12 text-center mt-2">
            <a class="text-muted fw-bold" href="{% url 'create-fault-report' %}">Click here</a> to report a fault
            <p>
                <i class="bi bi-arrow-left"></i> <a class="text-muted fw-bold" href="https://www.fhsfailities.com">Back to FHS</a>
            </p>
        </div>
        <!-- /.col -->
    </div>
    <!--end::Row-->
</form>
{% endblock %}

account/templates/front-end/admin/login-admin2.html
<html>
    <head>
        <title>Admin Log In</title>
    </head>
    <body>
        <div>
            <form action="{% url 'login-admin' %}" method="POST">
                {% csrf_token %}
                <label for="">Email</label>
                <input type="text" name="email">
                <label for="">Password</label>
                <input type="password" name="password">
                <button type="submit">Log In</button>
            </form>
        </div>
    </body>
</html>

account/templates/front-end/admin/permission-list.html
{% extends 'base-front-end/admin/base.html' %}
{% block content %}
<!--begin::App Main-->
<main class="app-main">
    <!--begin::App Content Header-->
    <div class="app-content-header">
        <!--begin::Container-->
        <div class="container-fluid">
            <!--begin::Row-->
            <div class="row">
                <div class="col-sm-6">
                    <h3 class="mb-0">Update Permissions</h3>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-end">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Update Permissions</li>
                    </ol>
                </div>
            </div>
            <!--end::Row-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::App Content Header-->
    <!--begin::App Content-->
    <div class="app-content">
        <!--begin::Container-->
        <div class="container-fluid">
            <!--begin::Row-->
            <div class="row g-4">
                <!--begin::Col-->
                <div class="col-12">
                    <div class="callout callout-info">
                        Alert message
                    </div>
                </div>
                <!--end::Col-->
                <!--begin::Col-->
                <div class="col-md-6">
                    <!--begin::Quick Example-->
                    <div class="card card-primary card-outline mb-4">
                        <!--begin::Form-->
                        <form action="{% url 'update-permissions-admin' %}" method="POST">
                            {% csrf_token %}
                            <!--begin::Body-->
                            <div class="card-body">
                                <input type="hidden" name="admin-id" value="{{ admin.id }}">
                                {% for permission in permissions %}
                                    <div class="mb-3">
                                        <input type="checkbox" {% if permission in admin.user_permissions.all %}checked{% endif %} name="permissions" value="{{ permission.id }}" class="pt-1" id="" aria-describedby="password" />{{ permission.name }}
                                    </div>
                                {% endfor %}
                            </div>
                            <!--end::Body-->
                            <!--begin::Footer-->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                            <!--end::Footer-->
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Quick Example-->
                </div>
                <!--end::Col-->
                <!--begin::Col-->
                <div class="col-md-6">
                </div>
                <!--end::Col-->
            </div>
            <!--end::Row-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::App Content-->
</main>
{% endblock %}